name: Check pull request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: read
  pull-requests: write

jobs:
  pr-validator:
    name: Run pull request checks
    runs-on: ubuntu-latest
    env:
      DEFRA_NUGET_PAT: ${{ secrets.GITHUB_TOKEN }}
      GVMS_API_CLIENT_ID: ${{ secrets.GVMS_API_CLIENT_ID }}
      GVMS_API_CLIENT_SECRET: ${{ secrets.GVMS_API_CLIENT_SECRET }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            10.0

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Check formatting
        run: dotnet csharpier check .

      - name: Log in to Docker Hub
        uses: DEFRA/cdp-build-action/docker-login@54ced5c5344c8b9620561a1628fe8f3d858e9871 # v1.5.0

      - name: Checkout trade-imports-gmr-local-env
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: DEFRA/trade-imports-gmr-local-env
          ref: 0.1.0
          path: trade-imports-gmr-local-env

      - name: Start trade-imports-gmr-local-env
        working-directory: trade-imports-gmr-local-env
        run: docker compose up --wait --wait-timeout 300 --quiet-pull

      - name: Run journey tests
        run: dotnet test --results-directory reports --report-html --report-html-filename index.html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: reports
          path: ./reports

      - name: Capture Docker Compose logs
        if: always()
        working-directory: trade-imports-gmr-local-env
        run: docker compose logs > logs.txt

      - name: Upload Docker Compose logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docker-compose-logs
          path: trade-imports-gmr-local-env/logs.txt
